---
seed: 1024

dataset:
  input_dim: 7
  output_dim: 1
  input_len: 12
  output_len: 3
  n_neighbors: 32
  dataloader: dataloader_all_sensors_seq2seq

model:
  name: hyper_graph_hyper_seq2seq_32x32_v1
  type: seq2seq

  geo_hiddens: [32,32]
  rnn_type: [MyGRUCell, HyperGRUCell]
  rnn_hiddens: [32, 32]
  graph_type: [HyperAttGraph, None]
  
training:
  batch_size: 2
  
  wd: 0
  lr: 0.01
  lr_decay_step: 7020
  lr_decay_factor: 0.1
  lr_min: 0.000002
  clip_gradient: 5

  use_sampling: True
  cl_decay_steps: 2000

  early_stop_metric: rmse
  early_stop_epoch: 60
